// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WooliesScraper.Tables;

#nullable disable

namespace WooliesScraper.Migrations
{
    [DbContext(typeof(BarcodeIndexContext))]
    [Migration("20240603034859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WooliesScraper.Tables.Barcode", b =>
                {
                    b.Property<int>("BarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarcodeId"));

                    b.HasKey("BarcodeId");

                    b.ToTable("Barcode");
                });

            modelBuilder.Entity("WooliesScraper.Tables.VendorStockCode", b =>
                {
                    b.Property<int>("VendorStockCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorStockCodeId"));

                    b.Property<int>("Barcode")
                        .HasColumnType("int");

                    b.Property<int?>("BarcodeId")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorStockCodeId");

                    b.HasIndex("BarcodeId");

                    b.ToTable("StockCodes");
                });

            modelBuilder.Entity("WooliesScraper.Tables.VendorStockCode", b =>
                {
                    b.HasOne("WooliesScraper.Tables.Barcode", null)
                        .WithMany("StockCodes")
                        .HasForeignKey("BarcodeId");
                });

            modelBuilder.Entity("WooliesScraper.Tables.Barcode", b =>
                {
                    b.Navigation("StockCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
